# Generated by Django 4.2.5 on 2024-03-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderName', models.CharField(max_length=100)),
                ('member1', models.CharField(max_length=100)),
                ('member2', models.CharField(max_length=100)),
                ('member3', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('domain', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
