# Generated by Django 4.2.5 on 2024-03-06 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liitapp', '0003_register_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='desg',
            new_name='designation',
        ),
    ]
