# Generated by Django 4.2.5 on 2024-03-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liitapp', '0004_rename_desg_register_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='uploaded_files/'),
        ),
    ]
