# Generated by Django 4.2.5 on 2024-03-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liitapp', '0005_register_uploaded_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='designation',
            new_name='designation1',
        ),
        migrations.AddField(
            model_name='register',
            name='designation2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='designation3',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='register',
            name='designation4',
            field=models.CharField(default='', max_length=100),
        ),
    ]
