# Generated by Django 4.2.5 on 2024-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liitapp', '0007_alter_register_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='uploaded_file',
            field=models.FileField(default='', upload_to='uploaded_files/'),
        ),
    ]
