# Generated by Django 4.2.5 on 2024-03-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liitapp', '0012_register_pdf_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='pdf_file',
        ),
    ]
